### ISSUE TITLE
Vinn tap tittel

### ISSUE THREAD

**Issue by JosteinEng** [JosteinEng/josteineng.github.io#10]
Mulig å fortelle at kampen er vunnet, tapt, eller uavgjort?

Eksempel: 
BRGN 2-1 Blabla (Vinn)

**Comment by hennnning** [comment]
Ja lett. Vi tester jo alt på vinn/uavgjort/tap for å farge teksten.

**Comment by JosteinEng** [comment]
Vi tekst for fargeblinde

Det er BRA UX design!!!

Kan ikke kun ha farge
