### ISSUE TITLE
Total statistikk

### ISSUE THREAD

**Issue by JosteinEng** [JosteinEng/josteineng.github.io#11]
Total statistikk på alle kampene

Logg record
Eksempel øverst på siden
Win-Tie-Loss Record: (8-2-0)

**Comment by hennnning** [comment]
Du får nok ikke noe logg da vi teknisk sett ikke har noe back end (enda). Les: server med database som lagrer ting.
Men det er vel strengt tatt ikke nødvendig heller da vi bare leacher på gamer.no sin api/database.

Dette er _litt_ overkill for hva du beskriver, men ser det finnes et bibliotek for statistikk i nettleser/javascript. Vi kan jo implementere det på sikt.
https://thisancog.github.io/statistics.js/

**Comment by JosteinEng** [comment]
Kan ikke du utføre noe 

If (4) er grønn
(3) rød
(1) blå

Record = 4-1-3
