### ISSUE TITLE
API er nede

### ISSUE THREAD

**Issue by JosteinEng** [JosteinEng/josteineng.github.io#18]
jeg har laget ny side for BRGN og ønsker å implementere API nå, men ser at den ikke funker.. den gamer.no/api lenken som scripten fetcher finnes ikke mer

**Comment by hennnning** [comment]
Den er sikkert flyttet igjen. Om du går til den vanlige linken for gamer kan du bruke console i nettleser for å se hvor den henter info fra. Under Network-tab skal det komme et XHR-dokument fra gamer.no/api/../matches når du oppdaterer siden.

[https://www.gamer.no/klubber/brgn/101211](url)

**Comment by JosteinEng** [comment]
På APIen så blir vi på noen kamper plassert på høyre og får "tap" selvom vi vant, hvorfor skjer det?

https://josteineng.github.io/Gamer%20API/gamerapi.html

**Comment by hennnning** [comment]
Oppdatert til nyeste versjon av API
